{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hoardr
  version: {{ version|replace("-", "_") }}

source:
  fn: hoardr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/hoardr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hoardr/hoardr_{{ version }}.tar.gz
  sha256: d929a69672ae4bbfea82202cdcf8d3a12f64e768edc5ce0b23a2ec902df3728d

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6 >=2.2.0
    - r-digest
    - r-rappdirs >=0.3.1
  run:
    - r-base
    - r-r6 >=2.2.0
    - r-digest
    - r-rappdirs >=0.3.1

test:
  commands:
    - $R -e "library('hoardr')"           # [not win]
    - "\"%R%\" -e \"library('hoardr')\""  # [win]
    - conda inspect linkages -p $PREFIX r-hoardr  # [not win]
    - conda inspect objects -p $PREFIX r-hoardr  # [osx]

about:
  home: https://github.com/ropensci/hoardr
  license: MIT
  license_file: LICENSE
  summary: Suite of tools for managing cached files, targeting use in other R packages. Uses
    'rappdirs' for cross-platform paths. Provides utilities to manage cache directories,
    including targeting files by path or by key; cached directories can be compressed
    and uncompressed easily to save disk space.
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
