travis:
  secure:
    BINSTAR_TOKEN: lRAQPocy58OwEEm6R1/rZbwpBUem4oBUFW3EwagPq5GR1qo8/POxN7Zet4/EtJGQ4CP9iJ8MOJInnRD8xu+6kv+EV4MK07oz1kWu3FXWJvXQjX+04bEzRdzWtxP3bUb1lzB0JXHz+RfCM7rf/ZI1i50MV/5Ood5H/yErUE0Hayw2vcs9OczaiD20t7xTT+JePoeEIzcl8qxaJM09ieL/e2W/fDJO2zRCQ4EjAUK7aOSLTnKioFsqY1UsPYfeOtfAGTlRBCR6hwk5LUUlJ6p2eAHuQOKNzcbVWovfztkM5ZbZdmD77+260mZ8w4oSUtZtMJudB5n6fNgCr0wvny4FJN87WhaVBvA0e4f1C2xosGMsoJXy+XdmT7nc92qd6WU8/0ufJtgnV1CEPJmUTaAYsRzPoQMhjLSGtl2LxW6Yyw1qknaeUlYikqWrION0+1u/0bAuV7Uod1rkjfcHrIIDGAnqrqsPNYwriCxwCIwhdVFhtKmPAugcSgiYsRbY74ByZlw4uSDf89RyKwlqDUNtL4YgZoWD7vfpjOlHvW5dZ292LkWYjAB5qa//iRgIXmI7TfBMD/BGVcc7JcNGV8pNWFS0ZPS8ICF+Gtb3jVJpQBE1zFY9ZL2tcFjobJGRFXLp+j9oNgdASH0U2x6WfeJ5n7N1KICZCnkmFrqv1TNldXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
