travis:
  secure:
    BINSTAR_TOKEN: UoRbwPF48suTvL9a1mZTZreLK10f6n1dS+bExHiW3lG6VTcqw0T8aA1O/A8siJBEXRDWiaZ1OFEi3bQdhPi9bgMsKWhyJKL/49mnn1JGu3bNncTw2ee1jLeh+qoKrEG2iSgtboLoqb7Ug+ZQmO7HjMMbKyq0IzUmT7YY/MXWLWnS9uPRV6mdBKr3RCnC77ImlVRvsJs8qYT2mwmgg0jSyXm+2X0uMXzBWl6thQlkyODKuZIXXcz0KIXgXSJ5Lui0wWhAzr2Tvcg5xmxz4kVgvZlwNjzj+JJucwl7hqHVq/n4G0Ybf0ZSxPF9UXyVTKbxmUV2+IepM7gTPPxBO8FozxqDU8eHgVzuBo3P6hM/lOdNSI4/O5UTUqpcltEmHHJ4WTmBOFWZ9XCNGbF38akuMamRII4rSWgtBnUIf64kVZbAY2EVjqEkt8fYjgA+pHpuKT5yoIYZF5avBZEoUhreoDe0Zg+NTyS47rM6Pa3DIwb29Xf2+GoFH/MmXn020zdDdGCvw0ygSI3HD98V1+jbfKbRW5dh3HYjdW2bVwHkkqyMzdJP6UIefMzhWAYwDO05IT9fpdCsZNLwkLx58K11nYwDfF7A6jUQSRhmnKPlosEb5RmWeIdG5tz/tFoBV6j0pldEuJNKb46cmuY+UpKKpEdMqgrW0aYjIIWvss+mP1E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
